//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestartManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestartManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Start-RestartManagerSession to start a session..
        /// </summary>
        internal static string Action_StartSession {
            get {
                return ResourceManager.GetString("Action_StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Stop-RestartManagerSession or pass -Force to end the current session..
        /// </summary>
        internal static string Action_StopSession {
            get {
                return ResourceManager.GetString("Action_StopSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Restart Manager.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is empty..
        /// </summary>
        internal static string Error_EmptyArgument {
            get {
                return ResourceManager.GetString("Error_EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active session..
        /// </summary>
        internal static string Error_NoSession {
            get {
                return ResourceManager.GetString("Error_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is already defined..
        /// </summary>
        internal static string Error_ServiceExists {
            get {
                return ResourceManager.GetString("Error_ServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is already active..
        /// </summary>
        internal static string Error_SessionExists {
            get {
                return ResourceManager.GetString("Error_SessionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting applications and services.
        /// </summary>
        internal static string RestartStatus {
            get {
                return ResourceManager.GetString("RestartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down applications and services.
        /// </summary>
        internal static string ShutdownStatus {
            get {
                return ResourceManager.GetString("ShutdownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were added since no file paths were detected..
        /// </summary>
        internal static string Warning_NoFiles {
            get {
                return ResourceManager.GetString("Warning_NoFiles", resourceCulture);
            }
        }
    }
}
